# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/infile/odoo_prism/odoo_json/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'picking_in_*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'odoo_picking_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/odoo_prism/odoo_json', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/infile/odoo_prism/odoo_json/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'picking_out_*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'odoo_picking_out', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/odoo_prism/odoo_json', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
#{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/outfile/odoo_prism/odoo_json/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'picking_conf_*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'odoo_picking_conf', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/odoo_prism/odoo_json', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
#{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/outfile/odoo_prism/odoo_json/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'inventory_*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'odoo_inventory', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/odoo_prism/odoo_json', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/outfile/odoo_prism/prism_xml/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'pos_*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'prism_po', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/odoo_prism/prism_xml', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/outfile/odoo_prism/prism_xml/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'orders_*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'prism_order', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/odoo_prism/prism_xml', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
#{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/infile/odoo_prism/prism_xml/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'WOC_*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'prism_woc', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/odoo_prism/prism_xml', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
#{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/infile/odoo_prism/prism_xml/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'SR_*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'prism_sr', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/odoo_prism/prism_xml', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'json', 'frommessagetype': u'odoo_picking_in_json', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'xml', 'tomessagetype': u'prism_purchase_xml', 'topartner': None, 'tscript': u'prism_purchase_json2xml'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'json', 'frommessagetype': u'odoo_picking_out_json', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'xml', 'tomessagetype': u'prism_order_xml', 'topartner': None, 'tscript': u'prism_order_json2xml'},
#{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'raw', 'frommessagetype': u'prism_woc', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'json', 'tomessagetype': u'odoo_picking_conf_json', 'topartner': None, 'tscript': u'prism_orderconf_raw2json'},
#{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'raw', 'frommessagetype': u'prism_sr', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'json', 'tomessagetype': u'odoo_inventory_json', 'topartner': None, 'tscript': u'prism_stockreport_raw2json'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'odoo_picking_in', 'fromeditype': u'json', 'frommessagetype': u'odoo_picking_in_json', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'odoo_2_prism_picking_in', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'prism_po', 'toeditype': u'xml', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'odoo_picking_out', 'fromeditype': u'json', 'frommessagetype': u'odoo_picking_out_json', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'odoo_2_prism_picking_out', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'prism_order', 'toeditype': u'xml', 'tomessagetype': u'', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
#{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'prism_woc', 'fromeditype': u'raw', 'frommessagetype': u'prism_woc', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'prism_2_odoo_picking_conf', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'odoo_picking_conf', 'toeditype': u'json', 'tomessagetype': u'odoo_picking_conf_json', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
#{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'prism_sr', 'fromeditype': u'raw', 'frommessagetype': u'prism_sr', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'prism_2_odoo_inventory', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'odoo_inventory', 'toeditype': u'json', 'tomessagetype': u'odoo_inventory_json', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
]
