# -*- coding: utf-8 -*-
import datetime
version = '3.1.0'
plugins = [
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/infile/odoo_dsv/odoo_json/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'picking_in_*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'odoo_picking_in', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/odoo_dsv/odoo_json', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/infile/odoo_dsv/odoo_json/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'picking_out_*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'odoo_picking_out', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/odoo_dsv/odoo_json', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/outfile/odoo_dsv/odoo_json/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'picking_conf_*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'odoo_picking_conf', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/odoo_dsv/odoo_json', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/outfile/odoo_dsv/odoo_json/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'inventory_*.json', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'odoo_inventory', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/odoo_dsv/odoo_json', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/outfile/odoo_dsv/dsv_xml/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'WEO_*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'dsv_weo', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/odoo_dsv/dsv_xml', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/outfile/odoo_dsv/dsv_xml/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'WSO_*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'dsv_wso', 'inorout': u'out', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/outfile/odoo_dsv/dsv_xml', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/infile/odoo_dsv/dsv_xml/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'WOC_*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'dsv_woc', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/odoo_dsv/dsv_xml', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'channel', 'apop': False, 'archivepath': u'botssys/infile/odoo_dsv/dsv_xml/archive', 'askmdn': u'no', 'certfile': None, 'charset': u'us-ascii', 'desc': None, 'filename': u'SR_*.xml', 'ftpaccount': u'', 'ftpactive': False, 'ftpbinary': False, 'host': u'', 'idchannel': u'dsv_sr', 'inorout': u'in', 'keyfile': None, 'lockname': u'', 'mdnchannel': u'', 'parameters': u'', 'path': u'botssys/infile/odoo_dsv/dsv_xml', 'port': 0, 'remove': True, 'rsrv1': None, 'rsrv2': None, 'rsrv3': None, 'secret': u'', 'sendmdn': u'no', 'starttls': False, 'syslock': False, 'testpath': u'', 'type': u'file', 'username': u''},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'json', 'frommessagetype': u'odoo_picking_in_json', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'raw', 'tomessagetype': u'dsv_weo', 'topartner': None, 'tscript': u'dsv_warehouseentryorder_json2raw'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'json', 'frommessagetype': u'odoo_picking_out_json', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'raw', 'tomessagetype': u'dsv_wso', 'topartner': None, 'tscript': u'dsv_warehouseshippingorder_json2raw'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'raw', 'frommessagetype': u'dsv_woc', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'json', 'tomessagetype': u'odoo_picking_conf_json', 'topartner': None, 'tscript': u'dsv_orderconf_raw2json'},
{'plugintype': u'translate', 'active': True, 'alt': u'', 'desc': None, 'fromeditype': u'raw', 'frommessagetype': u'dsv_sr', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': u'json', 'tomessagetype': u'odoo_inventory_json', 'topartner': None, 'tscript': u'dsv_stockreport_raw2json'},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'odoo_picking_in', 'fromeditype': u'json', 'frommessagetype': u'odoo_picking_in_json', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'odoo_2_dsv_picking_in', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'dsv_weo', 'toeditype': u'raw', 'tomessagetype': u'dsv_weo', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'odoo_picking_out', 'fromeditype': u'json', 'frommessagetype': u'odoo_picking_out_json', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'odoo_2_dsv_picking_out', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'dsv_wso', 'toeditype': u'raw', 'tomessagetype': u'dsv_wso', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'dsv_woc', 'fromeditype': u'raw', 'frommessagetype': u'dsv_woc', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'dsv_2_odoo_picking_conf', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'odoo_picking_conf', 'toeditype': u'json', 'tomessagetype': u'odoo_picking_conf_json', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': u'routes', 'active': True, 'alt': u'', 'defer': False, 'desc': None, 'fromchannel': u'dsv_sr', 'fromeditype': u'raw', 'frommessagetype': u'dsv_sr', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': u'dsv_2_odoo_inevntory', 'notindefaultrun': False, 'rsrv1': None, 'rsrv2': None, 'seq': 9999, 'testindicator': u'', 'tochannel': u'odoo_inventory', 'toeditype': u'json', 'tomessagetype': u'odoo_inventory_json', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
]
